# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='acces',
            field=models.BooleanField(default=True),
        ),
    ]
